2023-03-13 23:35:31,321 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Configure stats pid to 12892
2023-03-13 23:35:31,321 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\.config\wandb\settings
2023-03-13 23:35:31,321 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\settings
2023-03-13 23:35:31,321 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-13 23:35:31,321 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-13 23:35:31,321 INFO    MainThread:12892 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_233531-ypppestt\logs\debug.log
2023-03-13 23:35:31,322 INFO    MainThread:12892 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_233531-ypppestt\logs\debug-internal.log
2023-03-13 23:35:31,322 INFO    MainThread:12892 [wandb_init.py:init():532] calling init triggers
2023-03-13 23:35:31,322 INFO    MainThread:12892 [wandb_init.py:init():539] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.005, 'architecture': 'Homo-GNN', 'num_layers': 4, 'dataset': '1-HV-mixed--0-no_sw', 'epochs': 1000, 'activation': 'ReLu', 'dropout': 0.0, 'in_channels': 4, 'output_channels': 4, 'hidden_channels': 256, 'channel type': 'GraphConv', 'norm': 'BatchNorm'}
2023-03-13 23:35:31,322 INFO    MainThread:12892 [wandb_init.py:init():555] re-initializing run, found existing run on stack: axm1txtx
2023-03-13 23:35:31,323 INFO    MainThread:12892 [wandb_run.py:_finish():1854] finishing run cbml/OPF-GNN-Supervised-Homo/axm1txtx
2023-03-13 23:35:31,323 INFO    MainThread:12892 [jupyter.py:save_history():449] not saving jupyter history
2023-03-13 23:35:31,323 INFO    MainThread:12892 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-13 23:35:31,323 INFO    MainThread:12892 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-13 23:35:31,324 INFO    MainThread:12892 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-13 23:35:31,324 INFO    MainThread:12892 [wandb_run.py:_restore():2066] restore
2023-03-13 23:35:31,324 INFO    MainThread:12892 [wandb_run.py:_restore():2072] restore done
2023-03-13 23:35:39,031 INFO    MainThread:12892 [wandb_run.py:_footer_history_summary_info():3442] rendering history
2023-03-13 23:35:39,032 INFO    MainThread:12892 [wandb_run.py:_footer_history_summary_info():3474] rendering summary
2023-03-13 23:35:39,036 INFO    MainThread:12892 [wandb_run.py:_footer_sync_info():3398] logging synced files
2023-03-13 23:35:39,039 INFO    MainThread:12892 [wandb_init.py:init():588] starting backend
2023-03-13 23:35:39,039 INFO    MainThread:12892 [wandb_init.py:init():592] setting up manager
2023-03-13 23:35:39,040 INFO    MainThread:12892 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=spawn, using: spawn
2023-03-13 23:35:39,042 INFO    MainThread:12892 [wandb_init.py:init():599] backend started and connected
2023-03-13 23:35:39,050 INFO    MainThread:12892 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-13 23:35:39,051 INFO    MainThread:12892 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-13 23:35:39,051 INFO    MainThread:12892 [wandb_init.py:init():687] updated telemetry
2023-03-13 23:35:39,101 INFO    MainThread:12892 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-13 23:35:40,683 INFO    MainThread:12892 [wandb_run.py:_on_init():2134] communicating current version
2023-03-13 23:35:41,334 INFO    MainThread:12892 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-13 23:35:41,335 INFO    MainThread:12892 [wandb_init.py:init():775] starting run threads in backend
2023-03-13 23:35:45,298 INFO    MainThread:12892 [wandb_run.py:_console_start():2114] atexit reg
2023-03-13 23:35:45,298 INFO    MainThread:12892 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-13 23:35:45,298 INFO    MainThread:12892 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-13 23:35:45,298 INFO    MainThread:12892 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-13 23:35:45,298 INFO    MainThread:12892 [wandb_init.py:init():817] run started, returning control to user process
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Configure stats pid to 12892
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\.config\wandb\settings
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\settings
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_233859-mm7vtd3x\logs\debug.log
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_233859-mm7vtd3x\logs\debug-internal.log
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001A4106F36C8>
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:init():532] calling init triggers
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:init():539] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0005, 'architecture': 'Homo-GNN', 'num_layers': 4, 'dataset': '1-HV-mixed--0-no_sw', 'epochs': 1000, 'activation': 'ReLu', 'dropout': 0.0, 'in_channels': 4, 'output_channels': 4, 'hidden_channels': 256, 'channel type': 'GraphConv', 'norm': 'BatchNorm'}
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:init():555] re-initializing run, found existing run on stack: ypppestt
2023-03-13 23:38:59,574 INFO    MainThread:12892 [wandb_run.py:_finish():1854] finishing run cbml/OPF-GNN-Supervised-Homo/ypppestt
2023-03-13 23:38:59,574 INFO    MainThread:12892 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-13 23:38:59,574 INFO    MainThread:12892 [wandb_run.py:_restore():2066] restore
2023-03-13 23:38:59,575 INFO    MainThread:12892 [wandb_run.py:_restore():2072] restore done
2023-03-13 23:40:12,782 WARNING MsgRouterThr:12892 [router.py:message_loop():77] message_loop has been closed
