2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Configure stats pid to 12892
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\.config\wandb\settings
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\settings
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-13 23:38:59,572 INFO    MainThread:12892 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_233859-mm7vtd3x\logs\debug.log
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230313_233859-mm7vtd3x\logs\debug-internal.log
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:_jupyter_setup():438] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001A4106F36C8>
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:init():532] calling init triggers
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:init():539] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0005, 'architecture': 'Homo-GNN', 'num_layers': 4, 'dataset': '1-HV-mixed--0-no_sw', 'epochs': 1000, 'activation': 'ReLu', 'dropout': 0.0, 'in_channels': 4, 'output_channels': 4, 'hidden_channels': 256, 'channel type': 'GraphConv', 'norm': 'BatchNorm'}
2023-03-13 23:38:59,573 INFO    MainThread:12892 [wandb_init.py:init():555] re-initializing run, found existing run on stack: ypppestt
2023-03-13 23:38:59,574 INFO    MainThread:12892 [wandb_run.py:_finish():1854] finishing run cbml/OPF-GNN-Supervised-Homo/ypppestt
2023-03-13 23:38:59,574 INFO    MainThread:12892 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-13 23:38:59,574 INFO    MainThread:12892 [wandb_run.py:_restore():2066] restore
2023-03-13 23:38:59,575 INFO    MainThread:12892 [wandb_run.py:_restore():2072] restore done
2023-03-13 23:40:12,782 WARNING MsgRouterThr:12892 [router.py:message_loop():77] message_loop has been closed
2023-03-13 23:40:13,333 ERROR   MainThread:12892 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_init.py", line 567, in init
    self._wl._global_run_stack[-1].finish()
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_run.py", line 371, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_run.py", line 334, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_run.py", line 1845, in finish
    return self._finish(exit_code, quiet)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_run.py", line 1873, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_manager.py", line 187, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\service\service_sock.py", line 54, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
