2023-03-10 17:28:57,208 INFO    MainThread:14192 [wandb_setup.py:_flush():68] Configure stats pid to 14192
2023-03-10 17:28:57,209 INFO    MainThread:14192 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\.config\wandb\settings
2023-03-10 17:28:57,209 INFO    MainThread:14192 [wandb_setup.py:_flush():68] Loading settings from C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\settings
2023-03-10 17:28:57,209 INFO    MainThread:14192 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-10 17:28:57,209 INFO    MainThread:14192 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-10 17:28:57,210 INFO    MainThread:14192 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230310_172857-nxo54iu3\logs\debug.log
2023-03-10 17:28:57,210 INFO    MainThread:14192 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\canba\OneDrive\Masaüstü\OPFGNN\code\wandb\run-20230310_172857-nxo54iu3\logs\debug-internal.log
2023-03-10 17:28:57,210 INFO    MainThread:14192 [wandb_init.py:init():532] calling init triggers
2023-03-10 17:28:57,210 INFO    MainThread:14192 [wandb_init.py:init():539] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'Homo-GNN', 'dataset': '1-HV-mixed--0-no_sw', 'epochs': 100, 'activation': 'ReLu', 'dropout': 0.0}
2023-03-10 17:28:57,210 INFO    MainThread:14192 [wandb_init.py:init():555] re-initializing run, found existing run on stack: 5oohd4l4
2023-03-10 17:28:57,212 INFO    MainThread:14192 [wandb_run.py:_finish():1854] finishing run cbml/OPF-GNN-Supervised-Homo/5oohd4l4
2023-03-10 17:28:57,212 INFO    MainThread:14192 [jupyter.py:save_history():449] not saving jupyter history
2023-03-10 17:28:57,212 INFO    MainThread:14192 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-10 17:28:57,212 INFO    MainThread:14192 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-10 17:28:57,213 INFO    MainThread:14192 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-10 17:28:57,213 INFO    MainThread:14192 [wandb_run.py:_restore():2066] restore
2023-03-10 17:28:57,213 INFO    MainThread:14192 [wandb_run.py:_restore():2072] restore done
2023-03-10 17:30:54,433 INFO    MainThread:14192 [wandb_init.py:init():588] starting backend
2023-03-10 17:30:54,433 INFO    MainThread:14192 [wandb_init.py:init():592] setting up manager
2023-03-10 17:30:54,434 INFO    MainThread:14192 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=spawn, using: spawn
2023-03-10 17:30:54,436 INFO    MainThread:14192 [wandb_init.py:init():599] backend started and connected
2023-03-10 17:30:54,445 INFO    MainThread:14192 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-10 17:30:54,445 INFO    MainThread:14192 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-10 17:30:54,445 INFO    MainThread:14192 [wandb_init.py:init():687] updated telemetry
2023-03-10 17:30:54,489 INFO    MainThread:14192 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-10 17:31:24,791 WARNING MsgRouterThr:14192 [router.py:message_loop():77] message_loop has been closed
2023-03-10 17:31:24,791 WARNING MsgRouterThr:14192 [router.py:message_loop():77] message_loop has been closed
2023-03-10 17:31:24,868 ERROR   MainThread:14192 [wandb_init.py:init():1160] error
Traceback (most recent call last):
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_init.py", line 1133, in init
    run = wi.init()
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\wandb_init.py", line 733, in init
    cancel=True,
  File "C:\Users\canba\anaconda3\envs\code\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
